"""admin rework

Revision ID: 15d989bcf280
Revises: 3e6c69f10a89
Create Date: 2025-07-23 10:49:55.028540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15d989bcf280'
down_revision: Union[str, Sequence[str], None] = '3e6c69f10a89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',sa.Column('name', sa.VARCHAR(length=35), nullable=False))
    # ### end Alembic commands ###
