"""enable_basicallyeverything

Revision ID: 3e6c69f10a89
Revises:
Create Date: 2025-07-22 12:36:12.824602

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3e6c69f10a89"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questions",
        sa.Column("question", sa.Text(), nullable=True),
        sa.Column("options", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("answer", sa.Text(), nullable=True),
    )
    op.create_table(
        "stats",
        sa.Column("name", sa.VARCHAR(length=35), nullable=True),
        sa.Column("correctcount", sa.Integer(), nullable=True),
        sa.Column("result", sa.Text(), nullable=True),
        sa.Column("creationdate", sa.TIMESTAMP(), nullable=True),
    )
    op.create_table(
        "users",
        sa.Column("name", sa.VARCHAR(length=35), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=True),
        sa.Column("usertype", sa.Text(), nullable=True),
        sa.Column("creationdate", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("stats")
    op.drop_table("questions")
    # ### end Alembic commands ###
